name  = "BWI"
prefix = "bwi"
author = "Black Watch International"
[files]
 include = [
    "mod.cpp",
    "bwi.paa"
    ]
[version]
major = 1
minor = 0
patch = 0

[hemtt.build]
pdrive = "require"

[hemtt.check]
pdrive = "require"